### ISSUE TITLE
CleanArchitectureベースのPackage構成

### ISSUE THREAD

**Issue by halu5071** [Coding-Trip/CodingTripAndroid#12]
レイヤー分けを早めにしておきましょう。

**Comment by omuomugin** [comment]
- infra
  - api
  - model(ここは冗長かも) 
- model(domain)
- repository(domain)
- ui(presentation)
- util

domainをdomainで固めてもいいけどね。

**Comment by omuomugin** [comment]
あとクリーンアーキテクチャっていうかレイヤードアーキテクチャかなー
