### ISSUE TITLE
ドロワー

### ISSUE THREAD

**Issue by omuomugin** [Coding-Trip/CodingTripAndroid#3]
## Design
<img src="https://user-images.githubusercontent.com/16621708/34145180-33ed1474-e4d8-11e7-82a9-64b54e506cd1.png" width="320px" />

## アクション
- 設定
- コントリビューター一覧(予定)
- 運営者一覧(予定)

**Comment by nakker1218** [comment]
![navigationdrawer](https://user-images.githubusercontent.com/7314660/34166094-61f5c2b4-e521-11e7-8990-fd7b464cdaf5.png)
