### ISSUE TITLE
詳細画面1 (参加者一覧)

### ISSUE THREAD

**Issue by omuomugin** [Coding-Trip/CodingTripAndroid#4]
## Design

<img src="https://user-images.githubusercontent.com/16621708/34145285-a05b5e2c-e4d8-11e7-9579-10e9859074fe.png" width="320px" />

## アクション
- 参加者一覧が見れる
- プロフィール？

**Comment by nakker1218** [comment]
ここは、参加者一覧よりも発表者の情報とか資料が見れるほうが嬉しくない？

**Comment by omuomugin** [comment]
あーそれでもいいね。
毎回LT会とも限らないからあれかもと思った。

どっちかっていうとコンテンツみたいなのに近いかも。
